# Generated by Django 5.0.1 on 2024-02-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='couleur_patient',
            field=models.CharField(choices=[('B', 'Bleu'), ('R', 'Rouge'), ('J', 'Jaune')], default='Bleu', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='numero_secu',
            field=models.TextField(blank=True, help_text='Format: XXXXXXXXXXXXX XX', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tel_patient',
            field=models.CharField(blank=True, help_text='Format : +XX XXX XXX XXX', max_length=15, null=True),
        ),
    ]
