# Generated by Django 5.0.1 on 2024-02-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='fixed_schedule',
        ),
    ]
