# Generated by Django 5.0.1 on 2024-02-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_patient_couleur_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='couleur_medecin',
            field=models.CharField(choices=[('B', 'Bleu'), ('R', 'Rouge'), ('J', 'Jaune')], default='Bleu', max_length=20),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='profession',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='tel_medecin',
            field=models.CharField(blank=True, help_text='Format : +XX XXX XXX XXX', max_length=15, null=True),
        ),
    ]
