# Generated by Django 5.0.1 on 2024-02-21 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_medecin_couleur_medecin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.medecin'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.patient'),
        ),
    ]
