# Generated by Django 5.0.1 on 2024-02-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_slot_medecin_alter_slot_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='note',
            field=models.CharField(default='Aucunes notes', max_length=400),
            preserve_default=False,
        ),
    ]
