# Generated by Django 5.0.1 on 2024-03-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='profession',
            field=models.CharField(default='Médecin', max_length=25),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='tel_medecin',
            field=models.CharField(default='+33 455 456 457', help_text='Format : +XX XXX XXX XXX', max_length=15),
        ),
    ]
