# Generated by Django 5.0.1 on 2024-03-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_alter_medecin_profession_alter_medecin_tel_medecin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='profession',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='tel_medecin',
            field=models.CharField(help_text='Format : +XX XXX XXX XXX', max_length=15),
        ),
    ]
