# Generated by Django 5.0.1 on 2024-03-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_alter_medecin_couleur_medecin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='couleur_patient',
            field=models.CharField(choices=[('#0000FF', 'Bleu'), ('#FF0000', 'Rouge'), ('#FFFF00', 'Jaune')], default='#0000FF', max_length=7),
        ),
        migrations.AlterField(
            model_name='patient',
            name='numero_secu',
            field=models.CharField(blank=True, help_text='Format: XXXXXXXXXXXXX XX', max_length=16, null=True),
        ),
    ]
