# Generated by Django 5.0.1 on 2024-04-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_alter_patient_couleur_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='type_RDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.DurationField()),
                ('type', models.CharField(choices=[('D', 'Defaut')], default='D', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='numero_secu',
            field=models.CharField(default='1234567891234 56', help_text='Format: XXXXXXXXXXXXX XX', max_length=16),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tel_patient',
            field=models.CharField(default='+33 456 456 456', help_text='Format : +XX XXX XXX XXX', max_length=15),
        ),
    ]
