# Generated by Django 5.0.1 on 2024-04-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_type_rdv_alter_patient_numero_secu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_rdv',
            name='duree',
            field=models.DurationField(default='00:45:00'),
        ),
    ]
