# Generated by Django 5.0.1 on 2024-04-28 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_patient_type_rdv'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='type_rdv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.type_rdv'),
        ),
    ]
