# Generated by Django 5.0.1 on 2024-04-30 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0017_remove_patient_type_rdv_remove_medecin_type_rdv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='type_rdv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.typerdv'),
        ),
    ]
