# Generated by Django 5.0.1 on 2024-04-30 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0018_patient_type_rdv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typerdv',
            name='tel_medecin',
        ),
        migrations.AddField(
            model_name='typerdv',
            name='nom',
            field=models.CharField(default='Consultation', help_text='Type de RDV', max_length=25),
        ),
        migrations.AlterField(
            model_name='typerdv',
            name='duree',
            field=models.DurationField(default=datetime.timedelta(seconds=2700)),
        ),
    ]
