# Generated by Django 5.0.1 on 2024-04-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0019_remove_typerdv_tel_medecin_typerdv_nom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typerdv',
            old_name='medecins',
            new_name='medecin',
        ),
    ]
