# Generated by Django 5.0.1 on 2024-04-30 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0020_rename_medecins_typerdv_medecin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typerdv',
            name='medecin',
        ),
        migrations.AddField(
            model_name='typerdv',
            name='medecin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.medecin'),
        ),
    ]
