# Generated by Django 5.0.1 on 2024-05-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0021_remove_typerdv_medecin_typerdv_medecin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typerdv',
            name='nom',
            field=models.CharField(help_text='Type de RDV', max_length=25),
        ),
    ]
