# Generated by Django 5.0.1 on 2024-05-01 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0022_alter_typerdv_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='lundi',
        ),
        migrations.AddField(
            model_name='invitation',
            name='medecin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.medecin'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.patient'),
        ),
    ]
