# Generated by Django 5.0.1 on 2024-05-01 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0023_remove_invitation_lundi_invitation_medecin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='date_limite',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='duree_RDV',
            field=models.DurationField(default=datetime.timedelta(seconds=2700)),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='modif_RDV',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='nbr_RDV',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='nbr_semaine',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
