# Generated by Django 5.0.1 on 2024-05-03 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0025_invitation_date_limite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='duree_RDV',
        ),
    ]
